name: 'Run tests in Renode'
description: 'This action runs selected robot test suites in Renode and generates artifacts'
author: 'Antmicro'

branding:
  color: 'blue'
  icon: 'play-circle'

inputs:
  renode-version:
    description: 'Renode version'
    required: true
    default: 'latest'
  tests-to-run:
    description: 'Robot framework test paths'
    required: false
  renode-run-path:
    description: 'Path for renode-run artifacts. May be used to cache Renode between jobs'
    required: false
    default: '${{ runner.temp }}/renode-run'
  renode-arguments:
    description: 'Additional arguments passed to renode-test'
    required: false
    default: ''
  artifacts-path:
    description: 'Path where renode-test artifacts should be stored'
    required: false
    default: '.'
  gather-execution-metrics:
    description: 'Gather execution metrics for executed binaries'
    required: false
    default: 'no'
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/src/run_renode_test.sh
      shell: bash
      env:
        RENODE_VERSION: ${{ inputs.renode-version }}
        TESTS_TO_RUN: ${{ inputs.tests-to-run }}
        RENODE_RUN_DIR: ${{ inputs.renode-run-path }}
        RENODE_ARGUMENTS: ${{ inputs.renode-arguments }}
        ARTIFACTS_PATH: ${{ inputs.artifacts-path }}
        EXECUTION_METRICS: ${{ inputs.gather-execution-metrics }}
