name: 'Run tests in Renode'
description: 'This action runs selected robot test suites in Renode and generates artifacts'
author: 'Antmicro'

branding:
  color: 'blue'
  icon: 'play-circle'

inputs:
  renode-version:
    description: 'Renode version'
    required: true
    default: 'latest'
  tests-to-run:
    description: 'Robot framework test paths'
    required: true
    default: 'tests/**/*.robot'
  renode-path:
    description: 'Path for Renode installation. May be used to cache Renode between jobs'
    required: false
    default: '${{ runner.temp }}/renode'
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/src/run_renode_test.sh
      shell: bash
      env:
        RENODE_VERSION: ${{ inputs.renode-version }}
        TESTS_TO_RUN: ${{ inputs.tests-to-run }}
        RENODE_DIR: ${{ inputs.renode-path }}
