name: Test action

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      renode_revision:
        description: 'Renode git revision'
        required: false
        default: ''
      renode_repository:
        description: 'Renode git repository'
        required: false
        default: ''

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Download Renode
        uses: ./
        with:
          renode-revision: ${{ inputs.renode_revision || 'master' }}
          renode-repository: ${{ inputs.renode_repository || 'https://github.com/renode/renode' }}

      - name: Verify if Renode is persistent
        run: renode --version | grep "Renode v" || exit 1
        shell: bash

      - name: Run sample test
        uses: ./
        with:
          tests-to-run:  __tests__/hello_world.robot
          renode-revision: ${{ inputs.renode_revision || 'master' }}
          renode-repository: ${{ inputs.renode_repository || 'https://github.com/renode/renode' }}

      - name: Run sample test with metrics visualization
        uses: ./
        with:
          tests-to-run:  __tests__/profiling.robot
          artifacts-path: metrics
          gather-execution-metrics: yes
          renode-revision: ${{ inputs.renode_revision || 'master' }}
          renode-repository: ${{ inputs.renode_repository || 'https://github.com/renode/renode' }}

      - name: Upload results with metrics
        uses: actions/upload-artifact@v4
        with:
          name: metrics-${{ runner.os }}-${{ github.run_id }}
          path: metrics/*

      - name: Verify that renode-test also works under CMD/PowerShell on Windows
        run: renode-test __tests__/hello_world.robot
        shell: cmd
        if: ${{ runner.os == 'Windows' }}

  test-install-dependencies-input:
    strategy:
      matrix:
        inputs-install-dependencies: ['yes', 'no']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Try to build Renode
        id: try_build_renode
        uses: ./
        with:
          renode-revision: ${{ inputs.renode_revision || 'master' }}
          renode-repository: ${{ inputs.renode_repository || 'https://github.com/renode/renode' }}
          install-dependencies: 'false'
        if: ${{ matrix.inputs-install-dependencies != 'yes' }}
        continue-on-error: true

      - name: Check build status
        if: ${{ matrix.inputs-install-dependencies != 'yes' && steps.try_build_renode.outcome != 'failure' }}
        run: exit 1

      - name: Preinstall dependencies
        run: |
          source ubuntu-dependencies
          sudo apt-get -qqy update
          sudo apt-get -y install --no-install-recommends git automake cmake autoconf libtool g++ coreutils policykit-1 libgtk-3-dev uml-utilities gtk-sharp3 python3 python3-pip dotnet-sdk-8.0
        shell: bash
        if: ${{ matrix.inputs-install-dependencies != 'yes' }}

      - name: Build Renode
        uses: ./
        with:
          renode-revision: ${{ inputs.renode_revision || 'master' }}
          renode-repository: ${{ inputs.renode_repository || 'https://github.com/renode/renode' }}
          install-dependencies: ${{ matrix.inputs-install-dependencies }}

      - name: Run sample test
        uses: ./
        with:
          tests-to-run:  __tests__/hello_world.robot
          renode-revision: ${{ inputs.renode_revision || 'master' }}
          renode-repository: ${{ inputs.renode_repository || 'https://github.com/renode/renode' }}\

  test-disable-summary-generation-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run sample test
        uses: ./
        with:
          tests-to-run:  __tests__/hello_world.robot
          renode-revision: ${{ inputs.renode_revision || 'master' }}
          renode-repository: ${{ inputs.renode_repository || 'https://github.com/renode/renode' }}
          disable-summary-generation: 'yes'
