name: Test action

on: [push,pull_request,workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Download Renode
        uses: ./

      - name: Verify if Renode is persistent
        run: renode --version | grep "Renode v" || exit 1
        shell: bash

      - name: Run sample test
        uses: ./
        with:
           tests-to-run:  __tests__/hello_world.robot
